# Builds demo/ — the browser demo of the editor that runs the real Ruby model in
# WebAssembly (ruby.wasm), so anyone can try the plugin without SketchUp.
#
#   ruby scripts/build_demo.rb [out_dir]        # default: demo/
#
# The output is a static folder: the editor page, its assets, the vendored
# three.js, one generated Ruby bundle and a small boot script. GitHub Pages (or
# any static server) can serve it as is.
require 'json'
require 'fileutils'

ROOT = File.expand_path('..', __dir__)
OUT = File.expand_path(ARGV[0] || File.join(ROOT, 'demo'))
HTML = File.join(ROOT, 'src', 'skrine', 'ui', 'html')

# Load order of the pure-Ruby layer (no SketchUp API anywhere in here).
SOURCES = %w[
  version
  core/param_schema core/box core/part core/hardware core/layout core/sizing core/registry
  data/drawer_systems
  wardrobe/params
  data/column_modules
  wardrobe/corpus wardrobe/columns wardrobe/fronts wardrobe/drawers wardrobe/extras wardrobe/model
  export/scene export/cutlist
  ui/preview_service
].freeze

def strip_requires(code)
  # require_relative is meaningless in the bundle; everything is concatenated in order.
  code.gsub(/^\s*require_relative .*$\n/, '').gsub(%r{^\s*require ['"](json|cgi|fileutils)['"].*$\n}, '')
end

bundle = +"# Generated by scripts/build_demo.rb — do not edit.\n"
bundle << "require 'json'\nrequire 'cgi'\nrequire 'js'\n\n"
SOURCES.each do |rel|
  path = File.join(ROOT, 'src', 'skrine', "#{rel}.rb")
  abort "missing #{path}" unless File.file?(path)
  bundle << "# --- #{rel}.rb ---\n" << strip_requires(File.read(path, encoding: 'UTF-8')) << "\n"
end

presets = Dir[File.join(ROOT, 'presets', '*.json')].sort.map do |file|
  raw = JSON.parse(File.read(file, encoding: 'UTF-8'))
  name = raw.delete('_name') || File.basename(file, '.json').tr('-_', '  ').capitalize
  { 'file' => File.basename(file), 'name' => name, 'params' => raw }
end

bundle << <<~DEMO
  # --- demo bridge ---
  module Skrine
    # The browser demo has no file system and no SketchUp: presets are embedded and
    # "apply" only recomputes the preview. Everything else is the real code.
    module Demo
      PRESETS = JSON.parse(#{JSON.generate(JSON.generate(presets)).inspect}).freeze

      def self.type
        Core::Registry.fetch(:wardrobe)
      end

      def self.state(params)
        type.schema.merge_defaults(params || {})
      end

      def self.dispatch(name, payload)
        args = payload.to_s.empty? ? {} : JSON.parse(payload)
        case name
        when 'init'       then Editor::PreviewService.init_payload(type, state(args['state']))
        when 'preview'    then Editor::PreviewService.preview(type, args['state']).merge(seq: args['seq'])
        when 'apply'      then apply(args)
        when 'gallery'    then Editor::PreviewService.gallery(type, symbolize(PRESETS))
        when 'preset'     then preset(args['file'])
        when 'cutlist'    then cutlist(args['state'])
        else { errors: ["neznámy príkaz: \#{name}"] }
        end
      rescue StandardError => e
        { errors: ["Chyba: \#{e.class}: \#{e.message}"], warnings: [], info: {} }
      end

      def self.apply(args)
        pv = Editor::PreviewService.preview(type, args['state'])
        {
          errors: pv[:errors], warnings: pv[:warnings], info: pv[:info], seq: args['seq'],
          demo: 'V demo verzii sa model neprekresľuje – v SketchUpe by sa teraz prestavala skriňa.'
        }
      end

      def self.preset(file)
        entry = PRESETS.find { |p| p['file'] == file } || PRESETS.first
        Editor::PreviewService.init_payload(type, state(entry['params']))
      end

      def self.cutlist(params)
        st = state(params)
        layout = type.model_class.new(st).layout
        return { errors: layout.errors } unless layout.valid?

        { html: Export::Cutlist.new(layout.parts, layout.hardware, materials: st[:materials]).to_html }
      end

      def self.symbolize(list)
        list.map { |p| { file: p['file'], name: p['name'], params: p['params'] } }
      end

      # Called from JS: reads the call name and payload from window globals and
      # writes the JSON result back, so no Ruby source has to be built in JS.
      def self.run
        result = dispatch(JS.global[:skrineCall].to_s, JS.global[:skrinePayload].to_s)
        JS.global[:skrineResult] = JSON.generate(result)
        nil
      end
    end
  end
DEMO

FileUtils.rm_rf(OUT)
FileUtils.mkdir_p(File.join(OUT, 'libs'))
%w[index.html style.css icons.js cards.js drawing.js viewer3d.js measure.js form.js gallery.js app.js].each do |name|
  FileUtils.cp(File.join(HTML, name), File.join(OUT, name))
end
FileUtils.cp(File.join(HTML, 'libs', 'three.min.js'), File.join(OUT, 'libs', 'three.min.js'))
FileUtils.cp(File.join(HTML, 'libs', 'THREE-LICENSE.txt'), File.join(OUT, 'libs', 'THREE-LICENSE.txt'))
File.write(File.join(OUT, 'skrine.rb'), bundle)

# index.html: add the loading overlay and the demo bridge before app.js.
index = File.read(File.join(OUT, 'index.html'), encoding: 'UTF-8')
index = index.sub('<body>', <<~HEAD)
  <body class="demo">
    <div id="boot">
      <div class="boot-box">
        <h1>Skrine — demo</h1>
        <p id="boot-status">Načítavam Ruby do prehliadača…</p>
        <p class="boot-note">Beží tu ten istý parametrický model ako v SketchUpe, len preložený do WebAssembly.
        Prvé načítanie stiahne ~10 MB, potom je už v cache.</p>
      </div>
    </div>
HEAD
index = index.sub('  <script src="app.js"></script>', <<~TAIL.chomp)
    <script src="https://cdn.jsdelivr.net/npm/@ruby/3.3-wasm-wasi@2.10.1/dist/browser.umd.js"></script>
    <script src="boot.js"></script>
    <script src="app.js"></script>
TAIL
File.write(File.join(OUT, 'index.html'), index)

style = File.read(File.join(OUT, 'style.css'), encoding: 'UTF-8')
style << <<~CSS
  #boot { position: fixed; inset: 0; background: #fff; z-index: 50; display: flex; align-items: center; justify-content: center; }
  #boot.hidden { display: none !important; }
  .boot-box { max-width: 420px; text-align: center; font-size: 14px; }
  .boot-box h1 { font-size: 20px; margin: 0 0 10px; }
  #boot-status { font-weight: 600; }
  .boot-note { color: #666; font-size: 12px; line-height: 1.5; }
  body.demo #btn-apply::after { content: ' (demo)'; font-weight: 400; }
CSS
File.write(File.join(OUT, 'style.css'), style)

FileUtils.cp(File.join(ROOT, 'scripts', 'demo_boot.js'), File.join(OUT, 'boot.js'))
puts "demo built in #{OUT} (#{Dir[File.join(OUT, '**', '*')].size} files, bundle #{(bundle.bytesize / 1024.0).round} kB)"
